version: '3'

services:
####################
# setup node container
####################
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    command: yarn start

####################
# setup client container
####################
  client:
    build: ./client
    environment:
      - VUE_APP_PORT=${VUE_APP_PORT}
    expose:
      - ${VUE_APP_PORT}
    ports:
      - ${VUE_APP_PORT}:${VUE_APP_PORT}
    links:
      - server
    command: yarn start
